[features]
seeds = false
[programs.devnet]
gm_solana = "C4hazKmhxLEiGWKcpZvBAE2vd7DQQmjVNmkM3SJZhF9"

[registry]
url = "https://anchor.projectserum.com"

[provider]
cluster = "devnet"
wallet = "/home/faiz/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
